[tool.briefcase]
project_name = "First math game"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/firstmathgame"
license = "BSD license"
author = 'Goran Aviani'
author_email = "goran.aviani@gmail.com"

[tool.briefcase.app.firstmathgame]
formal_name = "First math game"
description = "My first application"
icon = "src/firstmathgame/resources/firstmathgame"
sources = ['src/firstmathgame']
requires = []


[tool.briefcase.app.firstmathgame.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.firstmathgame.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.firstmathgame.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.firstmathgame.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.firstmathgame.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
